version: '3'
services:
  nginx:
    build:
      context: ./docker-images/nginx/${NGINX_VERSION}
    ports:
      - 80:8000
    links:
      - phpfpm
      - redis:cache
    volumes:
      - ./src/app_data1:/var/www/html
      - ./src/sock_data1:/sock
      - ./src/nginx_log1:/var/log/nginx
    networks:
      - magento

  phpfpm:
    build:
      context: ./docker-images/php/${PHP_VERSION}
    links:
      - db1
    volumes:
      - ./docker-images/php/${PHP_VERSION}/.composer:/var/www/.composer
      - ./src/app_data1:/var/www/html
      - ./src/phpfpm_log1:/var/log
      - ./src/sock_data1:/sock
    networks:
      - magento

  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    volumes:
      - ./src/redis_data1:/data
    expose:
      - 6379
    networks:
      - magento

  cron:
    build:
      context: ./docker-images/php/${PHP_VERSION}
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db1
      - elasticsearch1
      - rabbitmq
    volumes:
      - ./src/app_data1:/var/www/html
      - ./src/sock_data1:/sock
    networks:
      - magento

  db1:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src/mysql_data1:/var/lib/mysql
      - ./src/mysql_log1:/var/log/mysql
    ports:
      - 3306:3306
    networks:
      - magento

  phpmyadmin:
    depends_on:
      - db1
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - magento

  elasticsearch1:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - ./src/es_data1:/usr/share/elasticsearch/data
      - ./src/es_log1:/var/log/elasticsearch
    networks:
      - magento

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - magento

networks:
  magento:
    driver: bridge
